apiVersion: v1
kind: Service
metadata:
  name: student-crud-grpc-service
spec:
  selector:
    app: student-crud-grpc
  ports:
    - protocol: TCP
      name: grpc
      port: 9090
      targetPort: 9090
    - protocol: TCP
      name: http
      port: 8080
      targetPort: 8080
  type: NodePort
